<?xml version="1.0" encoding="utf-8"?><Database Name="SynchProductionDB2" Class="SynchDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=omi6dwwsxk.database.windows.net;Initial Catalog=SynchProductionDB2;User ID=smladmin" SettingsObjectName="ERPIntegrationWorkerRole.Properties.Settings" SettingsPropertyName="SynchProductionDB2ConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.CloseRecord" Method="CloseRecord">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateUUID" Method="UpdateUUID">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="UUID" Parameter="uUID" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CountItemForBusiness" Method="CountItemForBusiness">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="item" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CountItemForBusinessResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CountItemForBusinessWithAccount" Method="CountItemForBusinessWithAccount">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="item" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="account" Type="System.Int32" DbType="Int" />
    <ElementType Name="CountItemForBusinessWithAccountResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CreateAccount" Method="CreateAccount">
    <Parameter Name="login" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(128)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="tier" Type="System.Int32" DbType="Int" />
    <Parameter Name="firstname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lastname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phone_number" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreateBusiness" Method="CreateBusiness">
    <Parameter Name="name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="zip" Type="System.Int32" DbType="Int" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="category" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="integration" Type="System.Int32" DbType="Int" />
    <Parameter Name="tier" Type="System.Int32" DbType="Int" />
    <Parameter Name="phone_number" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreateInventory" Method="CreateInventory">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="location" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="lead_time" Type="System.Int32" DbType="Int" />
    <Parameter Name="default_price" Type="System.Double" DbType="Float" />
    <Parameter Name="category" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreateProduct" Method="CreateProduct">
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="detail" Type="System.String" DbType="VarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreateProductInRecord" Method="CreateProductInRecord">
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="supplier" Type="System.Int32" DbType="Int" />
    <Parameter Name="customer" Type="System.Int32" DbType="Int" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="note" Type="System.String" DbType="VarChar(256)" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreateRecord" Method="CreateRecord">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="category" Type="System.Int32" DbType="Int" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="comment" Type="System.String" DbType="NVarChar(140)" />
    <Parameter Name="account" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreateSupplies" Method="CreateSupplies">
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Parameter Name="cid" Type="System.Int32" DbType="Int" />
    <Parameter Name="inventory_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteBusinessById" Method="DeleteBusinessById">
    <Parameter Name="bid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteInventoryByUpc" Method="DeleteInventoryByUpc">
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="bid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteProductsInRecord" Method="DeleteProductsInRecord">
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteSupplies" Method="DeleteSupplies">
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <Parameter Name="cid" Type="System.Int32" DbType="Int" />
    <Parameter Name="inventoryId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAccountBusiness" Method="GetAccountBusiness">
    <Parameter Name="aid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAccountBusinessResult">
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAccountById" Method="GetAccountById">
    <Parameter Name="aid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAccountByIdResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UUID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="session_id" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAccountByLogin" Method="GetAccountByLogin">
    <Parameter Name="login" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="GetAccountByLoginResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UUID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="session_id" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAccountEmail" Method="GetAccountEmail">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAccountEmailResult">
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllAccounts" Method="GetAllAccounts">
    <Parameter Name="bid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllAccountsResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UUID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="session_id" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllCustomers" Method="GetAllCustomers">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllCustomersResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="integration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllInventory" Method="GetAllInventory">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllInventoryResult">
      <Column Name="upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lead_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="default_price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllSuppliers" Method="GetAllSuppliers">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAllSuppliersResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="integration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetBusiness" Method="GetBusiness">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetBusinessResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="integration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCompleteChange" Method="GetCompleteChange">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCompleteChangeResult">
      <Column Name="record_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="record_title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="record_date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="record_category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="record_account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="record_comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="product_upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="product_quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_note" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCompleteReceipt" Method="GetCompleteReceipt">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCompleteReceiptResult">
      <Column Name="record_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="record_title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="record_date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="record_account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="record_comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="product_upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="product_quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="product_note" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="supplier_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="supplier_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="supplier_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCustomerById" Method="GetCustomerById">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="cid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCustomerByIdResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInventoryByUpc" Method="GetInventoryByUpc">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="GetInventoryByUpcResult">
      <Column Name="upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lead_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="default_price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetNRecordsFromLast" Method="GetNRecordsFromLast">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="last" Type="System.Int32" DbType="Int" />
    <Parameter Name="n" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetNRecordsFromLastResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="account" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetOrders" Method="GetOrders">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetOrdersResult">
      <Column Name="record_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="record_title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="record_date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="record_comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="record_account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="product_detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="product_quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="item_note" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="product_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="customer_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetProductByName" Method="GetProductByName">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="GetProductByNameResult">
      <Column Name="upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lead_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="default_price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetProductByUpc" Method="GetProductByUpc">
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="GetProductByUpcResult">
      <Column Name="upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetProductFromInventory" Method="GetProductFromInventory">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="GetProductFromInventoryResult">
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lead_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="default_price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetProductSummary" Method="GetProductSummary">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="GetProductSummaryResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="supplier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetReceipts" Method="GetReceipts">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetReceiptsResult">
      <Column Name="record_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="record_title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="record_date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="record_comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="record_account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="product_detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="product_quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="item_note" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="supplier_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="supplier_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="supplier_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecordById" Method="GetRecordById">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRecordByIdResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="account" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecords" Method="GetRecords">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRecordsResult">
      <Column Name="record_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecordsAfter" Method="GetRecordsAfter">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetRecordsAfterResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="account" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRecordsByTimeRange" Method="GetRecordsByTimeRange">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="start" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="end" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetRecordsByTimeRangeResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="account" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSessionId" Method="GetSessionId">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="session_id" Type="System.String" DbType="VarChar(512)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetSupplierById" Method="GetSupplierById">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="sid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSupplierByIdResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.HasInventory" Method="HasInventory">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.IncrementInventory" Method="IncrementInventory">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LinkAccountToBusiness" Method="LinkAccountToBusiness">
    <Parameter Name="aid" Type="System.Int32" DbType="Int" />
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Login" Method="Login">
    <Parameter Name="login" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(128)" />
    <ElementType Name="LoginResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="session_id" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Logout" Method="Logout">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PageBusinessForBusiness" Method="PageBusinessForBusiness">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="page_size" Type="System.Int32" DbType="Int" />
    <Parameter Name="offset" Type="System.Int32" DbType="Int" />
    <Parameter Name="reference" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="PageBusinessForBusinessResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PageInventoryForBusiness" Method="PageInventoryForBusiness">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="page_size" Type="System.Int32" DbType="Int" />
    <Parameter Name="offset" Type="System.Int32" DbType="Int" />
    <ElementType Name="PageInventoryForBusinessResult">
      <Column Name="upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lead_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="default_price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PageItemForBusiness" Method="PageItemForBusiness">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="page_size" Type="System.Int32" DbType="Int" />
    <Parameter Name="offset" Type="System.Int32" DbType="Int" />
    <Parameter Name="item" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="PageItemForBusinessResult">
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="upc" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lead_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="default_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PageRecordForBusiness" Method="PageRecordForBusiness">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="page_size" Type="System.Int32" DbType="Int" />
    <Parameter Name="offset" Type="System.Int32" DbType="Int" />
    <ElementType Name="PageRecordForBusinessResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="account" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PageRecordForBusinessWithAccount" Method="PageRecordForBusinessWithAccount">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="page_size" Type="System.Int32" DbType="Int" />
    <Parameter Name="offset" Type="System.Int32" DbType="Int" />
    <Parameter Name="account" Type="System.Int32" DbType="Int" />
    <ElementType Name="PageRecordForBusinessWithAccountResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="account" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchBusinessByName" Method="SearchBusinessByName">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SearchBusinessByNameResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="integration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchCustomerOrSupplier" Method="SearchCustomerOrSupplier">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="reference" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="query_string" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="SearchCustomerOrSupplierResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchInventory" Method="SearchInventory">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="reference" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="query_string" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="SearchInventoryResult">
      <Column Name="upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lead_time" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="default_price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchRecordByTitle" Method="SearchRecordByTitle">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="query_string" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="SearchRecordByTitleResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="business" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="account" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SendRecord" Method="SendRecord">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateAccountTier" Method="UpdateAccountTier">
    <Parameter Name="login" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="tier" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateBusinessById" Method="UpdateBusinessById">
    <Parameter Name="bid" Type="System.Int32" DbType="Int" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="zip" Type="System.Int32" DbType="Int" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="category" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phone_number" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateInventoryByUpc" Method="UpdateInventoryByUpc">
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="detail" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Parameter Name="bid" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateInventoryLeadTime" Method="UpdateInventoryLeadTime">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="lead_time" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateInventoryLocation" Method="UpdateInventoryLocation">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="location" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateProductUpc" Method="UpdateProductUpc">
    <Parameter Name="new_upc" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="old_upc" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateRecordTitle" Method="UpdateRecordTitle">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSessionId" Method="UpdateSessionId">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="session_id" Type="System.String" DbType="VarChar(512)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreateHistoryRecord" Method="CreateHistoryRecord">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="title" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="category" Type="System.Int32" DbType="Int" />
    <Parameter Name="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="comment" Type="System.String" DbType="NVarChar(140)" />
    <Parameter Name="account" Type="System.Int32" DbType="Int" />
    <Parameter Name="date" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetBusinessesWithIntegration" Method="GetBusinessesWithIntegration">
    <Parameter Name="integration" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetBusinessesWithIntegrationResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="integration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCompleteOrder" Method="GetCompleteOrder">
    <Parameter Name="business" Type="System.Int32" DbType="Int" />
    <Parameter Name="rid" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetCompleteOrderResult">
      <Column Name="record_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="record_title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="record_date" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="record_account" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="record_comment" Type="System.String" DbType="NVarChar(140)" CanBeNull="true" />
      <Column Name="product_upc" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="product_quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="product_note" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="product_detail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="customer_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="customer_email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>